blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from pylog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pylog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/pylog/urls.py
from django.urls import path, re_path
from . import views
from .feeds import LatestPostFeed

app_name = 'pylog'

urlpatterns = [
    path('', views.portfolio, name='portfolio'),
    path('pylog/', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # re_path(r'^$', views.PostListView.as_view(), name='post_list'),
    re_path(
        r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    re_path(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    path('feed/', LatestPostFeed(), name='post_feed'),
]

blog/pylog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    image = models.ImageField(null=True, blank=True, height_field=0, width_field=0,
                              upload_to="static/images/uploads/%Y/%B/%d")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICE, default='draft')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, related_name='blog_post', on_delete=models.CASCADE)
    body = models.TextField()

    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('pylog:post_detail', args=[self.publish.year,
                                                  self.publish.strftime('%m'),
                                                  self.publish.strftime('%d'),
                                                  self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/pylog/forms.py
from django import forms
from .models import Comment


class EmailPostForms(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

    # def clean(self):
    #     cleaned_data = super(CommentForm, self).clean()
    #     name = cleaned_data.get('name')
    #     email = cleaned_data.get('email')
    #     message = cleaned_data.get('body')
    #     if not name and not email and not body:
    #         raise forms.ValidationError('You have to write something!')

blog/pylog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from .forms import EmailPostForms, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.db.models import Count


def post_list(request, tag_slug=None):
    object_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(tag, slug=tag_slug)
        object_list = object_list.filter(tag__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page', 1)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'post/detail.html', {'post': post,
                                                'comments': comments,
                                                'comment_form': comment_form,
                                                'similar_posts': similar_posts})


def portfolio(request):
    return render(request, 'post/portfolio.html')


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForms(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} ({cd["email"]}) recommends you reading "{post.title}"'
            message = f'Read "{post.title}" at {post_url}\n\n{cd["name"]}\'s comments: {cd["comments"]}'
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForms()
    return render(request, 'post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.3).order_by('-similarity')
    return render(request,
                  'post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog/pylog/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Ahmed Zahid">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static "/favicon.ico" %}"/>
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,700|Lato" rel="stylesheet">
    <!-- Reset css -->
    <link type="text/css" rel="stylesheet" href="{% static "/css/reset.css" %}">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Bootstra css -->
    <!-- <link type="text/css" rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}"> -->
    <!-- Materialize css-->
    <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}"  media="screen,projection"/>
    <!-- Custom css -->
    <link type="text/css" rel="stylesheet" href="{% static "/scss/styles.css" %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %} {{ post.title }} {% endblock %}</title>
</head>

    <header class="header_container" role="banner">
        <div class="profile_pic">
            <a href="{% url 'pylog:post_list' %}"><img class="circle" width=150px height=150px alt="Ahmed Zahid" src="{% static "images/Ahmed_Zahid_br.png" %}" onmouseover="this.src='{% static "images/Ahmed_Zahid_cr.png" %}'" onmouseout="this.src='{% static "images/Ahmed_Zahid_br.png" %}'" /></a>
        </div>
        <div class="title_wrapper">
            <h1>{% block name %} Ahmed ZJ {% endblock %}</h1>
            <p class="description">{% block description %} Development | Books | Poetry{% endblock %}</p>
            <ul>
                <li class="social_link_list">
                    <a class="github_link" href="https://github.com/AhmedZahid098" target="_blank"> <i class="fa fa-github fa-2x" style=color:#fff> </i> </a>
                </li>
                <li class="social_link_list">
                    <a class="linkedin_link" href="https://www.linkedin.com/in/ahmed-zahid-122946a6/" target="_blank"> <i class="fa fa-linkedin fa-2x" style=color:#0077B5> </i> </a>
                </li>
                <li class="social_link_list">
                    <a class="googleplus_link" href="https://plus.google.com/+AhmedZahidZJ" target="_blank"> <i class="fa fa-google-plus fa-2x" style=color:#d34836> </i> </a>
                </li>
                <li class="social_link_list">
                    <a class="twitter_link" href="https://twitter.com/AhmedZahid098" target="_blank"> <i class="fa fa-twitter fa-2x" style=color:#00aced> </i> </a>
                </li>
            </ul>
        </div>
        <div class="nav_heading">
            <ul>
                <li class="nav_content">
                    <a title="Blog" href="{% url 'pylog:post_list' %}">Lifelog</a>
                </li>
                <li class="nav_content">
                    <a title="Portfolio" href="{% url 'pylog:portfolio' %}">Portfolio</a>
                </li>
            </ul>
        </div>
    </header>

    <main class="container">
        {% block content %}
        <!-- Insert here the Portfolio, Contact and PyLog -->
        {% endblock %}
    </main>

    <footer class="footer_wrapper grey darken-3">
        <div class="footer_text">
            <p> <em>
                &copy;
                2018·<a href="{% url 'pylog:post_list' %}">Ahmed ZJ</a>
                All rights reserved
            </em>
            </p>
        </div>
    </footer>

    <!-- Materialize js -->
    <script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <!-- fb commnets -->
    <!-- <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script> -->
</body>
</html

blog/pylog/templates/pagination.html

<span aria-label="Page-navigation">
    {% if posts.has_other_pages %}
        <ul class="pagination">
            {% if posts.has_previous %}
                <li class="page-item hoverable">
                    <a class="page-link waves-effect waves-light" href="?page={{ posts.previous_page_number }}">&laquo; Previous</a>
                </li>
            {% endif %}
            {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                    <li id="pg-color-change" class="page-item active hoverable">
                        <a class="page-link waves-effect waves-light" href="#">{{ i }}</a>
                    </li>
                {% else %}
                    <li class="page-item hoverable">
                        <a class="page-link waves-effect waves-light" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if posts.has_next %}
                <li class="page-item hoverable">
                    <a class="page-link waves-effect waves-light" href="?page={{ posts.next_page_number }}">Next &raquo;</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
</span>

blog/pylog/templates/post/Contact.html
{% extend "blog.html" %}
{% block content %}
<head>
    <link type="text/css" rel="stylesheet" href="reset.css">
</head>
<div>
    <main>
        <article class="contact">
            <h1>Contact</h1>
            <div>
                <form action="">
                    <p>
                        Your Name (required)<br>
                        <input type="text" name="Name"><br>
                    </p>
                    <p>
                        Your Email (required)<br>
                        <input type="text" name="Email"><br>
                    </p>
                    <p>
                        Subject<br>
                        <input type="text" name="Subject"><br>
                    </p>
                    <p>
                        Your Message<br>
                        <span>
                            <textarea name="your_message" class="message" cols="40" rows="10"></textarea><br>
                        </span>
                    </p>
                    <p>
                        <input type="submit" name="submit" value="Send"><br>
                    </p>

                </form>
            </div>
        </article>
        <aside class="subscription">

        </aside>
    </main>
</div>
{% endblock %}

blog/pylog/templates/post/detail.html
{% extends "base.html" %}
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <article class="white-text">

        <div id="card_transparency" class="card">
            <div class="card-content">
                <h1>{{ post.title }}</h1>
                <small>Published {{ post.publish }} by {{ post.author }}</small>
            </div>
            {% if post.image %}
            <div class="card-image">
                <img src="{{ post.image.url }}" class="" alt="{{ post.title }}" height=auto width=100%>
            </div>
            {% endif %}
            <div class="card-content">
                <p class="">{{ post.body|markdown }}</p>
            </div>
            <p class="card-content"><a href="{% url "pylog:post_share" post.id %}">Share post</a></p>
        </div>

        <!-- <div class="total_comments">
            {% with comments.count as total_comments %}
                <p>{{ total_comments }} comment{{ total_comments|pluralize }}</p>
            {% endwith %}
        <br>
            {% for comment in comments %}
                {{ comment.body|linebreaks }}
                <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
                {% empty %}
                <p>There are no comments yet.</p>
            {% endfor %}
        </div> -->
        <!-- <div class="fb-comments" data-href="{{ post.get_absolute_url }}" data-numposts="5"></div> -->
        <!-- <div>
            {% if new_comment %}
                <p>Your comment has been added.</p>
            {% else %}
                <p>Add a new comment</p>
            <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
            </form>
            {% endif %}
        </div> -->

    </article>

    <aside class="sidebar center-align">

        <div id="card_transparency" class="similar_posts card">
            <h2>Similar posts</h2>
            {% for post in similar_posts %}
            <p><a href="{{ post.get_absolute_url }}"></a>{{ post.title }}</p>
            {% empty %}
            <p class="card-content">There are no similar posts yet.</p>
            {% endfor %}
            <div class="feed card-content">
                <p>I've written {% total_posts %} posts so far.</p>
                <p><a href="{% url "pylog:post_feed" %}">Subscribe to my RSS feed</a></p>
            </div>
        </div>


        <div id="card_transparency" class="latest_posts card">
            <h3>Latest Posts</h3>
            <div class="card-content"><p>{% show_latest_posts 3 %}</p></div>
        </div>

        <!-- <div class="most_commented_post">
            <h3>Most commented posts</h3>
            {% get_most_commented_posts as most_commented_posts %}
                {% for post in most_commented_posts %}
                    <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
                {% endfor %}
        </div> -->

    </aside>

{% endblock %}

blog/pylog/templates/post/latest_posts.html

{% for post in latest_posts %}
  <p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </p>
{% endfor %}

blog/pylog/templates/post/list.html
{% extends "base.html" %}
{% load blog_tags %}

{% block title %} AhmedZJ {% endblock %}

{% block content %}
    <article class="wrapper_content_list">
        {% for post in posts %}
        <div class="card blue-grey darken-4 center-align hoverable">
            {% if post.image %}
            <div class="card-image">
                <img class="responsive-img" src="{{ post.image.url }}" class="" alt="{{ post.title }}" height=auto; width=100%>
            </div>
            {% endif %}
            <div class="card-content">
                <a href="{{ post.get_absolute_url }}"><h2 class="">{{ post.title }}</h2></a>
                <small>Published {{ post.publish }} by {{ post.author }}</small>
            </div>
            <div class="card-content">
                <p>{{ post.body|markdown|truncatewords:20|linebreaks }}</p>
            </div>
            <div class="card-action">
                <a href="{{ post.get_absolute_url }}" class="btn waves-effect waves-light blue-grey darken-3 hoverable">Read more</a>
            </div>

            <P class="card-content">
                <em>#</em>
                {% for tag in post.tags.all %}
                <a class="card-action" href="{% url "pylog:post_list_by_tag" tag.slug %} ">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </P>

        </div>
        {% endfor %}


    </article>
    <div class="center-align">
        {% include "pagination.html" with page=posts %}
    </div>
    <div class="">
        <div class="fb-comments" data-href="{% url 'pylog:post_list' %}" data-numposts="5"></div>
    </div>

    <aside class="sidebar center-align">
        <div class="">
            <div class="card blue-grey darken-4">
                <p class="card-content">
                    <span class="">I've written {% total_posts %} posts so far. I would love to have your response !</span>
                    <div class="card-content">
                        <a class="card-action" href="{% url "pylog:post_feed" %}">Subscribe to RSS feed</a>
                    </div>
                </p>
            </div>
        </div>
        <div class="">
            <div class="card blue-grey darken-4">
                <h3>Latest Posts</h3>
                <div class="card-content">
                    <p class="card-action">{% show_latest_posts 4 %}</p>
                </div>
            </div>
        </div>

    </aside>


{% endblock %}

blog/pylog/templates/post/portfolio.html
{% extends "base.html" %}
{% load staticfiles %}
<head>
    {% block title %} Ahmed ZJ Portfolio {% endblock %}
</head>

{% block description %} Web Developer | Electrical Engineer {% endblock %}

{% block name %} Ahmed Zahid {% endblock %}

{% block content %}

    <article class="">
        <div class="skills center-align">
            <h2 class="skills_title">Technical Skills</h2>
            <h3 class="languages">Programming Languages:</h3>
            <div class="languages_list">
                <i class="material-icons languages_icon">computer</i>
                <ul class="lists ">
                    <li>HTML</li>
                    <li>CSS</li>
                    <li>Sass</li>
                    <li>Javascript</li>
                    <li>Python</li>
                    <li>SQL</li>
                    <!-- <li>PHP</li> -->
                    <!-- <li>SQL</li> -->
                </ul>
            </div>
            <h3 class="tools">Tools, Frameworks and Libraries:</h3>
            <div class="tools_list">
                <i class="material-icons tools_icon">build</i>
                <ul class="lists ">
                    <li>Git</li>
                    <li>Github</li>
                    <li>Gulp</li>
                    <li>Django</li>
                    <li>Bootstrap</li>
                    <li>Postgeresql</li>
                    <!-- <li>Vue</li>
                    <li>React</li>
                    <li>WordPress</li>
                    <li>Laravel</li> -->
                </ul>
            </div>
            <h3 class="softwares">Softwares:</h3>
            <div class="softwares_list">
                <i class="material-icons softwares_icon">adb</i>
                <ul class="">
                    <li>Windows</li>
                    <li>Linux</li>
                    <li>Atom</li>
                    <li>AutoCAD</li>
                    <li>Genex Assistant</li>
                    <li>Genex Probe</li>
                </ul>
            </div>
        </div>
        <div class="work">
            <h2 class="">Work Experience</h2>
            <h3 class="">Web Developer</h3>
            <span>
                <a href="">Freelance</a><span class="label_underheadings"><small> • Feb’18 – Current</small></span>
            </span>
            <ul class="">
                <li>Worked on HTML/CSS/Sass/SQL</li>
                <li>Created a Blog using Python django framework</li>
                <li>Working on PHP, Javascript and Postgeresql</li>
            </ul>
            <hr>
            <h3 class="">RF Engineer</h3>
            <span>
                <a href="http://wi-tribe.pk/" target="_blank">Wi-tribe LTE-Advance</a><small> • Aug’17 – Feb’18p</small>
            </span>
            <ul class="">
                <li>Collection, Analysis and reporting writing of Drive Test (DT) Data</li>
                <li>Performing SSV’s of rollout LTE sites (Throughput testing, latency check, ping test, PCI conflict check, mode-3 verification)</li>
                <li>Prepare analysis and simulation reports, develop presentations, write test plans and perform evaluation</li>
                <li>Provide technical support in installation, operation, maintenance and repair of radio frequency in LTE advance system</li>
                <li>Perform to characterize, quantify and optimize electrical and RF frequency performance of wireless headset systems and components</li>
            </ul>
            <hr>
            <h3 class="">Management Trainee Engineer</h3>
            <span>
                <a href="http://atconconstruction.com/">Atcon</a><small> • May’17 – July’17</small>
            </span>
            <ul class="">
                <li>Interprets Electrical drawings and studies the contract documents and applicable standards or specifications prior to execution of work</li>
                <li>Manages directly and provide engineering and technical supports to all the electrical work groups at site</li>
                <li>Coordinates with Client / Consultant’s representatives for any site instructions and inspection of works</li>
                <li>Submits site daily reports, inspection requests, estimates and all applicable monitoring reports on regular basis or as required</li>
                <li>Continually review the contractor’s construction schedule during the progress of site works with regards to MEP services</li>
            </ul>
            <hr>
            <h3 class="">Intern Engineer</h3>
            <span>
                <a href="http://pel.com.pk/">Pak Electron Limited</a><small> • Jan’17 – Mar’17</small>
            </span>
            <ul class="">
                <li>Learn and support in carrying out design of different Transformers and Energy Meters and engineering calculations, preparation</li>
                <li>Read and understand NTDC/WAPDA, IEC, IEEE, ANSI, etc. standards and get equipment data according to these standards</li>
                <li>Perform detailed calculations to compute and establish manufacturing, construction, and installation standards and specifications</li>
            </ul>
        </div>

        <div class="projects">
            <h2>Latest Projects</h2>
            <span>
                <a href="http://wi-tribe.pk/4853-2/"><h3>Optimization and Testing of LTE-Advance network</h3></a><small class="container">• Aug’17 – Feb’18</small>
            </span>
            <p>I was responsible for testing and optimizing the LTE-Advance network sites located in city Lahore. All the testing and optimization was performed using Huawei softwares, Genex Probe and Genex Assistant. I was also handling customer complaints and suggesting RF solutions.</p>
        </div>
        <div class="personals">
            <h2>Personal Website</h2>
            <h3><a href="blog.html">AhmedZJ.com</a></h3>
            <span class="label_underheadings">Creator, Writer, Administrator • Feb’18-Current</span>
            <ul class="">
                <li>Personal blog about programming, web development, design, and more</li>
                <li>Perform system administration through SSH on a VPS running Ubuntu</li>
            </ul>
        </div>
    </article>

    <aside class="top_left">
        <div class="education">
            <h2>Education</h2>
            <h3>University of Management and Technology</h3>
            <span>
                <a href="https://www.umt.edu.pk/">School of Engineering</a><small> • 2012-2016</small>
            </span>
            <span><b>Bachelor of Science</b> in Electrical Engineering
            <p><b>Certification:</b></p></span>
            <ul class="">
                <li>Hafiz-e-Quran</li>
                <li>Sleep Management</li>
                <li>Stress Management</li>
            </ul>
        </div>
        <div class="hobbies">
            <h2>Activities/Hobbies</h2>
            <h3>Outdoor Recreation</h3>
            <p>Hiking, travelling, swimming, biking and snooker are in my hobbies</p>
            <div class=" showcase_images container">
                <img class="p_images img-responsive" src="{% static "images/Atabad_Lake.jpg" %}" alt="Atabad Lake">
                <img class="p_images img-responsive" src="{% static "images/Atabad_Lake2.jpg" %}" alt="Atabad Lake">
                <img class="p_images img-responsive" src="{% static "images/Babusar Top.jpg" %}" alt="Babusar Top">
                <img class="p_images img-responsive" src="{% static "images/Challas-Ferry_Meadows.jpg" %}" alt="Dangerous road to Ferry Meadows">
                <img class="p_images img-responsive" src="{% static "images/Gilgit.jpg" %}" alt="Gilgit">
                <img class="p_images img-responsive" src="{% static "images/KhunjrabPass.jpg" %}" alt="KhunjrabPass(China-Pakistan border)">
            </div>
        </div>
        <div class="volunteer">
            <h2>Volunteer Work</h2>
            <h3>Funds Collection</h3>
            <p>I used to collect funds for the needy students at a campaign held each year at University of Management and Technology throughout the four years of my graduation</p>
        </div>
    </aside>

{% endblock %}

blog/pylog/templates/post/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "pylog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blog/pylog/templates/post/share.html
{% extends "base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h2>E-mail successfully sent</h2>
        <p>"{{ post.title }}" was successfully sent by e-mail.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}